### PR TITLE
Final updates

### PR DESCRIPTION
**Pull request by taylorperkins**
Removed all modal things. In the end, it makes the javascript simpler. All of the content fits on a single card, and you can add/remove the content from the modal with "on hover" CSS instead. 

This PR does a few things: 
* Puts all the contact info directly below the name. This makes the bottom of the card less cluttered.
* Adds in a "Demo" button that replaces the "More" button. Instead of a modal, it just opens up a new tab in the user's browser that plays their demo if they have one! 
* Added in an iframe _per card_. I thought this was a bit nicer than having the iframes at the top.. Definitely a lot easier to search for someone and play their podcast.

Final look!
Screen Shot 2020-06-27 at 2 00 54 PM

The picture will change on hover if the student uploaded a separate pic, same with the bio! 

Additionally, tried to re-organize the CSS a bit in a way that follows the structural flow of the cards

### CODE REVIEW

**Comment by taylorperkins** [comment]
Also, please don't merge until Monday! There are some students still getting their videos together. Would love to do this only once haha

**Comment by unewsome** [comment]
Your view looks great! I like that you made it so the students' pictures change when you hover over them,  I like all the info being right under their picture... 

My picture and local upload looks a little different...
image

Also, which file should I go in to possibly resize the group picture.

**Comment by unewsome** [comment]
Oh and love the "Demo" button!!!

**Comment by taylorperkins** [comment]
@unewsome 
Good point out! The bio / reelthemin sections are set to a certain height (I think 150px). With that in mind, there comes a situation where either of those content groups could get bigger than 150px. In that scenario, I have decided to make those boxes "scrollable" so the size of the box doesn't change. This helps with the overall layout. Unfortunately, what I didn't notice, is that the scroll bars always exist if you're using windows. That's not something I can test out and fix on my computer unfortunately :/ I _think_ I may know how to fix that.. But you will definitely have to test it out for me again haha. 

Regarding the images! All original images should be placed in the "assets/img/original" folder. Then, you would run the "resizing images" notebook within the utilities folder. And finally, you would run the "make sons" notebook in the utilities folder. That should update everything

**Comment by taylorperkins** [comment]
@unewsome Ok.. Just added in another commit that should hide the scrollbar. Please check it one more time and let me know if it worked for you!

**Pull request merged**
